export const COMMON_GET_WINDOW_WIDTH = "COMMON_GET_WINDOW_WIDTH"
export const COMMON_OPEN_DRAWER = "COMMON_OPEN_DRAWER"
export const COMMON_CLOSE_DRAWER = "COMMON_CLOSE_DRAWER"

export const COMMON_COLOR_MAP = "COMMON_COLOR_MAP"

export const TAG_GETLIST = "TAG_GETLIST"
export const CATRGORY_GETLIST = "CATRGORY_GETLIST"

export const AUTH_OPEN_AUTHMODAL = "AUTH_OPEN_AUTHMODAL"
export const AUTH_CLOSE_AUTHMODEL = "AUTH_CLOSE_AUTHMODEL"

export const USER_LOGIN = "USER_LOGIN"
export const USER_REGISTER = "USER_REGISTER"
export const USER_LOGINOUT = "USER_LOGINOUT"